name: Deploy Python App to Azure Web App - rajbhog123

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # REQUIRED for Azure OIDC login
      contents: read   # Allows repo read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_374F0351701E4F89B8147247B5E83C5F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D95E70631A5E4C4681593C14F61AB2C6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CE581E954AD446E8A29CDD23B4AE78D8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rajbhog123'
          slot-name: 'Production'
          package: .
